config/routes.rb
Rails.application.routes.draw do

  resources :requests, only: [:new, :create]
  devise_for :admins
  root to: "user/home#index"

  # resources :reports
  # resources :newsletters
  devise_for :reporters
  resources :suscriptions, only:[:new, :create]
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/reporter', to: 'reporter/application#index'
  get '/quienes-somos', to: 'application#about'
  get '/contacto', to: 'application#contact'
  get '/noticias', to: 'application#reports'
  get '/admin', to: 'admin/application#index'
  get '/user', to: 'user/home#index'
  get '/admin/search', to: 'admin/application#search'




  namespace :admin do
    resources :biddings
    resources :projects
    resources :businesses
    resources :categories
    resources :project_temps
    resources :bidding_temps
    resources :requests, only:[:show, :index, :destroy]
    resources :sectors

  end

  namespace :user do
    resources :project_temps, only:[:show, :index]
    resources :bidding_temps, only:[:show, :index]
    resources :projects, only:[:show, :index]
  end

  namespace :reporter do
    resources :suscriptions, only:[:show, :index]
    resources :reports
    resources :newsletters do
      member do
        put :send_by_email
      end
    end
  end

end

app/models/project_temp.rb
class ProjectTemp < ApplicationRecord
  searchkick

  def search_data
      {
        title: title,
        country: country,
        sector_name: sector_name,
        client: client,
        region: region,
        owner: owner,
        current_phase: current_phase,
        responsible: responsible
      }
  end
end

app/controllers/admin/project_temps_controller.rb
class Admin::ProjectTempsController < Admin::ApplicationController
  before_action :set_project_temp, only: [:show, :edit, :update, :destroy]

  # GET /project_temps
  # GET /project_temps.json
  def index
    @project_temps = ProjectTemp.paginate(:page => params[:page], :per_page => 25)



    # @found = ProjectTemp.search(params['search'], fields: [:title, :country, :sector_name, :client, :region, :owner, :current_phase, :responsible])
    # if @found.length == 0
    #   @found = ProjectTemp.paginate(:page => params[:page], :per_page => 25)
    # end
    #
    @found_sector =  ProjectTemp.search(params['sector_name'], fields: [:sector_name], :per_page => 25)
    if @found_sector.length == 0
      @found_sector = ProjectTemp.paginate(:page => params[:page], :per_page => 25)
    end
    # query = params[:query].presence || "*"
    # conditions = {}
    # conditions[:sector_name] = params[:sector_name] if params[:sector_name].present?
    # conditions[:country] = params[:country] if params[:country].present?
    # @found_sector = ProjectTemp.search query, where: conditions

    @found_sector = ProjectTemp.search(params[:sector_name], fields: [:sector_name]).results &
                    ProjectTemp.search(params[:country], fields: [:country]).results &
                    ProjectTemp.search(params[:region], fields: [:region]).results
    if @found_sector.length == 0
      @found_sector = ProjectTemp.paginate(:page => params[:page], :per_page => 25)
    end

  end

  # GET /project_temps/1
  # GET /project_temps/1.json
  def show
  
  end

  # GET /project_temps/new
  def new
    @project_temp = ProjectTemp.new
  end

  # GET /project_temps/1/edit
  def edit
  end

  # POST /project_temps
  # POST /project_temps.json
  def create
    @project_temp = ProjectTemp.new(project_temp_params)

    respond_to do |format|
      if @project_temp.save
        format.html { redirect_to [:admin, @project_temp], notice: 'Project temp was successfully created.' }
        format.json { render :show, status: :created, location: @project_temp }
      else
        format.html { render :new }
        format.json { render json: @project_temp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /project_temps/1
  # PATCH/PUT /project_temps/1.json
  def update
    respond_to do |format|
      if @project_temp.update(project_temp_params)
        format.html { redirect_to [:admin, @project_temp], notice: 'Project temp was successfully updated.' }
        format.json { render :show, status: :ok, location: @project_temp }
      else
        format.html { render :edit }
        format.json { render json: @project_temp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /project_temps/1
  # DELETE /project_temps/1.json
  def destroy
    @project_temp.destroy
    respond_to do |format|
      format.html { redirect_to admin_project_temps_url, notice: 'Project temp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def pdfkit

  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project_temp
      @project_temp = ProjectTemp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_temp_params
      params.require(:project_temp).permit(:title, :detail_title, :country, :region, :sector_name, :types, :investment, :production, :client, :owner, :location, :description, :current_phase, :responsible, :contract_type, :latest_information, :contact_name, :contact_company, :contact_job, :contact_phone, :contact_address, :full_contact, :adjudications, :history, :main_works, :main_teams, :main_supplies, :main_services)
    end
end

app/controllers/user/project_temps_controller.rb
class User::ProjectTempsController < User::ApplicationController
  before_action :set_project_temp, only: [:show, :edit, :update, :destroy]

  # GET /project_temps
  # GET /project_temps.json
  def index
    @project_temps = ProjectTemp.all
    @found_sector =  ProjectTemp.search(params['sector_name'], fields: [:sector_name])
    if @found_sector.length == 0
      @found_sector = ProjectTemp.all
    end
    # query = params[:query].presence || "*"
    # conditions = {}
    # conditions[:sector_name] = params[:sector_name] if params[:sector_name].present?
    # conditions[:country] = params[:country] if params[:country].present?
    # @found_sector = ProjectTemp.search query, where: conditions

    @found_sector = ProjectTemp.search(params[:sector_name], fields: [:sector_name]).results &
                    ProjectTemp.search(params[:country], fields: [:country]).results &
                    ProjectTemp.search(params[:region], fields: [:region]).results
    if @found_sector.length == 0
      @found_sector = ProjectTemp.all
    end
  end

  # GET /project_temps/1
  # GET /project_temps/1.json
  def show
    respond_to do |format|
     format.html
     format.pdf do
     render pdf: "Your_filename",
     template: "user/project_temps/show.html.erb",
     layout: 'pdf_temp.html'

   end
  end

  end

  # GET /project_temps/new
  def new
    @project_temp = ProjectTemp.new
  end

  # GET /project_temps/1/edit
  def edit
  end

  # POST /project_temps
  # POST /project_temps.json
  def create
    @project_temp = ProjectTemp.new(project_temp_params)

    respond_to do |format|
      if @project_temp.save
        format.html { redirect_to [:user, @project_temp], notice: 'Project temp was successfully created.' }
        format.json { render :show, status: :created, location: @project_temp }
      else
        format.html { render :new }
        format.json { render json: @project_temp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /project_temps/1
  # PATCH/PUT /project_temps/1.json
  def update
    respond_to do |format|
      if @project_temp.update(project_temp_params)
        format.html { redirect_to [:user, @project_temp], notice: 'Project temp was successfully updated.' }
        format.json { render :show, status: :ok, location: @project_temp }
      else
        format.html { render :edit }
        format.json { render json: @project_temp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /project_temps/1
  # DELETE /project_temps/1.json
  def destroy
    @project_temp.destroy
    respond_to do |format|
      format.html { redirect_to user_project_temps_url, notice: 'Project temp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project_temp
      @project_temp = ProjectTemp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_temp_params
      params.require(:project_temp).permit(:title, :detail_title, :country, :region, :sector_name, :types, :investment, :production, :client, :owner, :location, :description, :current_phase, :responsible, :contract_type, :latest_information, :contact_name, :contact_company, :contact_job, :contact_phone, :contact_address, :full_contact, :adjudications, :history, :main_works, :main_teams, :main_supplies, :main_services)
    end
end

app/helpers/project_temps_helper.rb
module ProjectTempsHelper
end

app/views/admin/project_temps/_form.html.erb
<%= form_for [:admin, @project_temp], :html => { :class => "form-horizontal project_temp" } do |f| %>

  <% if @project_temp.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@project_temp.errors.count, "error") %> prohibited this project_temp from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @project_temp.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>
  <div class="form-group">
    <%= f.label :detail_title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :detail_title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:detail_title) %>
  </div>
  <div class="form-group">
    <%= f.label :country, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :country, :class => 'form-control' %>
    </div>
    <%=f.error_span(:country) %>
  </div>
  <div class="form-group">
    <%= f.label :region, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :region, :class => 'form-control' %>
    </div>
    <%=f.error_span(:region) %>
  </div>
  <div class="form-group">
    <%= f.label :sector_name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :sector_name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:sector_name) %>
  </div>
  <div class="form-group">
    <%= f.label :types, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :types, :class => 'form-control' %>
    </div>
    <%=f.error_span(:types) %>
  </div>
  <div class="form-group">
    <%= f.label :investment, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :investment, :class => 'form-control' %>
    </div>
    <%=f.error_span(:investment) %>
  </div>
  <div class="form-group">
    <%= f.label :production, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :production, :class => 'form-control' %>
    </div>
    <%=f.error_span(:production) %>
  </div>
  <div class="form-group">
    <%= f.label :client, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :client, :class => 'form-control' %>
    </div>
    <%=f.error_span(:client) %>
  </div>
  <div class="form-group">
    <%= f.label :owner, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :owner, :class => 'form-control' %>
    </div>
    <%=f.error_span(:owner) %>
  </div>
  <div class="form-group">
    <%= f.label :location, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :location, :class => 'form-control' %>
    </div>
    <%=f.error_span(:location) %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :description, :class => 'form-control', size: "20x6" %>
    </div>
    <%=f.error_span(:description) %>
  </div>
  <div class="form-group">
    <%= f.label :current_phase, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :current_phase, :class => 'form-control' %>
    </div>
    <%=f.error_span(:current_phase) %>
  </div>
  <div class="form-group">
    <%= f.label :responsible, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :responsible, :class => 'form-control' %>
    </div>
    <%=f.error_span(:responsible) %>
  </div>
  <div class="form-group">
    <%= f.label :contract_type, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :contract_type, :class => 'form-control' %>
    </div>
    <%=f.error_span(:contract_type) %>
  </div>
  <div class="form-group">
    <%= f.label :latest_information, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :latest_information, :class => 'form-control' %>
    </div>
    <%=f.error_span(:latest_information) %>
  </div>
  <div class="form-group">
    <%= f.label :contact_name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :contact_name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:contact_name) %>
  </div>
  <div class="form-group">
    <%= f.label :contact_company, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :contact_company, :class => 'form-control' %>
    </div>
    <%=f.error_span(:contact_company) %>
  </div>
  <div class="form-group">
    <%= f.label :contact_job, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :contact_job, :class => 'form-control' %>
    </div>
    <%=f.error_span(:contact_job) %>
  </div>
  <div class="form-group">
    <%= f.label :contact_phone, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :contact_phone, :class => 'form-control' %>
    </div>
    <%=f.error_span(:contact_phone) %>
  </div>
  <div class="form-group">
    <%= f.label :contact_address, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :contact_address, :class => 'form-control' %>
    </div>
    <%=f.error_span(:contact_address) %>
  </div>
  <div class="form-group">
    <%= f.label :full_contact, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :full_contact, :class => 'form-control' %>
    </div>
    <%=f.error_span(:full_contact) %>
  </div>
  <div class="form-group">
    <%= f.label :adjudications, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :adjudications, :class => 'form-control' %>
    </div>
    <%=f.error_span(:adjudications) %>
  </div>
  <div class="form-group">
    <%= f.label :history, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :history, :class => 'form-control', size: "20x6" %>
    </div>
    <%=f.error_span(:history) %>
  </div>
  <div class="form-group">
    <%= f.label :main_works, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :main_works, :class => 'form-control' %>
    </div>
    <%=f.error_span(:main_works) %>
  </div>
  <div class="form-group">
    <%= f.label :main_teams, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :main_teams, :class => 'form-control' %>
    </div>
    <%=f.error_span(:main_teams) %>
  </div>
  <div class="form-group">
    <%= f.label :main_supplies, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :main_supplies, :class => 'form-control' %>
    </div>
    <%=f.error_span(:main_supplies) %>
  </div>
  <div class="form-group">
    <%= f.label :main_services, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :main_services, :class => 'form-control', size: "20x5" %>
    </div>
    <%=f.error_span(:main_services) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                admin_project_temps_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/admin/project_temps/edit.html.erb
<%- model_class = ProjectTemp -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/project_temps/index.html.erb
<%- model_class = ProjectTemp -%>

<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<!-- <%= form_tag admin_project_temps_path, method: :get do %>
      <input name="search" type="text" placeholder="Busque aquí...">
      <button type="submit">Buscar</button>
<% end %> -->
<%= form_tag admin_project_temps_path, method: :get do %>
  <%= 'Sector' %>
  <%= select_tag :sector_name, options_for_select(['*','Mineria', 'Energia', 'Industrial', 'Forestal', 'Infraestructura', 'Sanitario']) %>
  <%= 'Pais' %>
  <%= select_tag :country, options_for_select(['*',["Chile"], 'Bolivia', 'Peru', 'Guatemala', 'Argentina', 'Ecuador', 'Panamá','Colombia','Uruguay','República Dominicana',
    'México','Venezuela']) %>
  <%= 'Region' %>
  <%= select_tag :region, options_for_select(['*', ['I - Tarapacá', {class: "Chile"}], ['II - Antofagasta', {class: "Chile"}], ['III - Atacama', {class: "Chile"}], ['IV - Coquimbo', {class: "Chile"}], ['V - Valparaíso', {class: "Chile"}],
    ['VI - Libertador General Bernardo O´Higgins', {class: "Chile"}], ['VII - Maule', {class: "Chile"}],
    ['VIII - Bío-Bío', {class: "Chile"}],['IX - Araucanía', {class: "Chile"}], ['X - Los Lagos', {class: "Chile"}], ['XI - Aysén del General Carlos Ibánez del Campo', {class: "Chile"}],
    ['XII - Magallanes y de la Antártica Chilena', {class: "Chile"}], ['Región Metropolitana', {class: "Chile"}],['XIV - Los Rios', {class: "Chile"}], ['XV - Arica y Parinacota', {class: "Chile"}],
    ['Amazonas', {class: "Peru"}], ['Áncash', {class: "Peru"}], ['Apurímac', {class: "Peru"}], ['Arequipa', {class: "Peru"}], ['Ayacucho', {class: "Peru"}], ['Cajamarca', {class: "Peru"}],
    ['Callao33​', {class: "Peru"}], ['Cusco', {class: "Peru"}],['Huancavelica', {class: "Peru"}], ['Huánuco', {class: "Peru"}], ['Ica', {class: "Peru"}], ['Junín', {class: "Peru"}],
    ['La Libertad', {class: "Peru"}], ['Lambayeque', {class: "Peru"}], ['Lima Metropolitana', {class: "Peru"}], ['Lima (departamento)', {class: "Peru"}], ['Loreto', {class: "Peru"}],
    ['Madre de Dios', {class: "Peru"}], ['Moquegua', {class: "Peru"}], ['Pasco', {class: "Peru"}], ['Piura', {class: "Peru"}], ['Puno', {class: "Peru"}],
    ['San Martín', {class: "Peru"}], ['Tacna', {class: "Peru"}], ['Tumbes', {class: "Peru"}], ['Ucayali', {class: "Peru"}], ['Buenos Aires', {class: "Argentina"}],
    ['Catamarca', {class: "Argentina"}], ['Chaco', {class: "Argentina"}], ['Chubut', {class: "Argentina"}], ['Córdoba', {class: "Argentina"}], ['Corrientes', {class: "Argentina"}],
    ['Entre Ríos', {class: "Argentina"}], ['Formosa', {class: "Argentina"}], ['Jujuy', {class: "Argentina"}], ['La Pampa', {class: "Argentina"}], ['La Rioja', {class: "Argentina"}],
    [ 'Mendoza', {class: "Argentina"}], ['Misiones', {class: "Argentina"}], ['Neuquén', {class: "Argentina"}], ['Río Negro', {class: "Argentina"}], ['Salta', {class: "Argentina"}],
    ['San Juan', {class: "Argentina"}], ['San Luis', {class: "Argentina"}], ['Santa Cruz', {class: "Argentina"}], ['Santa Fe', {class: "Argentina"}], ['Santiago del Estero', {class: "Argentina"}],
    ['Tierra del Fuego', {class: "Argentina"}], ['Antártida e Islas del Atlántico Sur', {class: "Argentina"}], ['Tucumán', {class: "Argentina"}]]) %>

  <%= submit_tag "Buscar", name: nil %>
<% end %>
  <button> <%= link_to "Mostrar todos",admin_project_temps_path %> </button>




  <select id="region" name="region">
  <option value="0">Select Street</option>
  <option value="1">Street 1</option>
  <option value="1">Street 2</option>
  <option value="1">Street 3</option>
  <option value="2">Street 4</option>
  <option value="2">Street 5</option>
  <option value="2">Street 6</option>
  <option value="1200">Street 7</option>
  <option value="1200">Street 8</option>
  <option value="1200">Street 9</option>
  </select>




  <!-- <body ng-app="">

  <%= form_tag admin_project_temps_path, method: :get do %>
  <%= 'Sector' %>
  <%= select_tag :sector_name, options_for_select(['*','Mineria', 'Energia', 'Industrial', 'Forestal', 'Infraestructura', 'Sanitario']) %>
    Pais:
  <%= select_tag :country, options_for_select(['','Chile', 'Bolivia', 'Peru', 'Guatemala', 'Argentina', 'Ecuador', 'Panamá','Colombia','Uruguay','República Dominicana',
      'México','Venezuela']), :ng => {:model => "pais"} %>
    <%= submit_tag "Buscar", name: nil %>
  <% end %>

  <div ng-switch="pais">
      <div ng-switch-when="Chile">
        <%= "Chile" %>
        <%= select_tag :region, options_for_select(['*', 'I - Tarapacá', 'II - Antofagasta', 'III - Atacama', 'IV - Coquimbo', 'V - Valparaíso', 'VI - Libertador General Bernardo O´Higgins', 'VII - Maule',
          'VIII - Bío-Bío','IX - Araucanía', 'X - Los Lagos', 'XI - Aysén del General Carlos Ibánez del Campo', 'XII - Magallanes y de la Antártica Chilena',
          'Región Metropolitana','XIV - Los Rios', 'XV - Arica y Parinacota']) %>
      </div>
      <div ng-switch-when="Peru">
        <%= "Perú" %>
        <%= select_tag :region, options_for_select(['*', 'Amazonas', 'Áncash', 'Apurímac', 'Arequipa', 'Ayacucho', 'Cajamarca', 'Callao33​',
          'Cusco','Huancavelica', 'Huánuco', 'Ica', 'Junín',
          'La Libertad','Lambayeque', 'Lima Metropolitana', 'Lima (departamento)', 'Loreto', 'Madre de Dios', 'Moquegua',
          'Pasco', 'Piura', 'Puno', 'San Martín', 'Tacna', 'Tumbes', 'Ucayali']) %>
      </div>
      <div ng-switch-when="Argentina">
        <%= "Argentina" %>
        <%= select_tag :region, options_for_select(['Buenos Aires', 'Catamarca', 'Chaco', 'Chubut', 'Córdoba', 'Corrientes', 'Entre Ríos',
          'Formosa','Jujuy', 'La Pampa', 'La Rioja', 'Mendoza',
          'Misiones','Neuquén', 'Río Negro', 'Salta', 'San Juan', 'San Luis', 'Santa Cruz',
          'Santa Fe', 'Santiago del Estero', 'Tierra del Fuego, Antártida e Islas del Atlántico Sur', 'Tucumán']) %>
      </div>
  </div>
  </div> -->


<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:Numero) %></th>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:country) %></th>
      <th><%= model_class.human_attribute_name(:region) %></th>
      <th><%= model_class.human_attribute_name(:owner) %></th>
      <th><%= model_class.human_attribute_name(:sector_name) %></th>
      <th><%= model_class.human_attribute_name(:updated_at) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <% i = 0 %>
  <tbody>
    <% @found_sector.each do |project_temp| %>
      <% i = i +1 %>
      <tr>
        <td><%= i %>
        <td><%= link_to project_temp.id, admin_project_temp_path(project_temp) %></td>
        <td><%= project_temp.title %></td>
        <td><%= project_temp.country %></td>
        <td><%= project_temp.region %></td>
        <td><%= project_temp.owner %></td>
        <td><%= project_temp.sector_name %></td>
        <td><%=l project_temp.updated_at %></td>
        <% if project_temp.updated_at >= "Wed, 24 Jan 2018 00:13:25 +0000" %>
          <td><button type="button" class="btn btn-success">Listo</button></td>
        <% else %>
          <td><button type="button" class="btn btn-danger">No Listo</button></td>

        <% end %>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      admin_project_temp_path(project_temp), :class => 'btn btn-info btn-xs' %>
          <%= link_to t('.edit', :default => t("helper s.links.edit")),
                      edit_admin_project_temp_path(project_temp), :class => 'btn btn-primary btn-xs' %>
          <!-- <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      admin_project_temp_path(project_temp),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %> -->
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<ul class="" align="center">
    <%= will_paginate @project_temps %>
</ul>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_admin_project_temp_path,
            :class => 'btn btn-primary' %>
<script>
  $('#country').change(function(){
      $('#region option').hide();
      $('#region option[class="'+$(this).val()+'"]').show()
      console.log($(this).val())

   });
</script>

app/views/admin/project_temps/new.html.erb
<%- model_class = ProjectTemp -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>