config/routes.rb
Rails.application.routes.draw do

  resources :requests, only: [:new, :create]
  devise_for :admins
  root to: "user/home#index"

  # resources :reports
  # resources :newsletters
  devise_for :reporters
  resources :suscriptions, only:[:new, :create]
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/reporter', to: 'reporter/application#index'
  get '/quienes-somos', to: 'application#about'
  get '/contacto', to: 'application#contact'
  get '/noticias', to: 'application#reports'
  get '/admin', to: 'admin/application#index'
  get '/user', to: 'user/home#index'
  get '/admin/search', to: 'admin/application#search'




  namespace :admin do
    resources :biddings
    resources :projects
    resources :businesses
    resources :categories
    resources :project_temps
    resources :bidding_temps
    resources :requests, only:[:show, :index, :destroy]
    resources :sectors

  end

  namespace :user do
    resources :project_temps, only:[:show, :index]
    resources :bidding_temps, only:[:show, :index]
    resources :projects, only:[:show, :index]
  end

  namespace :reporter do
    resources :suscriptions, only:[:show, :index]
    resources :reports
    resources :newsletters do
      member do
        put :send_by_email
      end
    end
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/bidding.rb
class Bidding < ApplicationRecord
  has_and_belongs_to_many :items_involved
  has_one :business
  has_one :country
  has_one :sector
end

app/models/bidding_temp.rb
class BiddingTemp < ApplicationRecord
  searchkick

  def search_data
      {
        title: title,
        country: country,
        sector: sector,
        bidding_company: bidding_company
      }
  end
end

app/models/business.rb
class Business < ApplicationRecord
  has_and_belongs_to_many :biddings
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :projects_categories 
  enum kind: [:item, :types, :adjudications, :main_works, :main_services, :main_teams, :main_supplies, :items_involved,
              :client, :owner, :region, :country, :project_type]
end

app/models/client.rb
class Client < Category
end

app/models/country.rb
class Country < Category
  has_and_belongs_to_many :biddings
  has_and_belongs_to_many :projects
  default_scope { where(kind: 'country') }
end

app/models/item.rb
class Item < Category
  has_and_belongs_to_many :projects
  default_scope { where(kind: 'item') }
end

app/models/main_work.rb
class MainWork < Category
  has_and_belongs_to_many :projects
  default_scope { where(kind: 'main_works') }
end

app/models/newsletter.rb
class Newsletter < ApplicationRecord
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/project.rb
class Project < ApplicationRecord
  has_and_belongs_to_many :items
  has_and_belongs_to_many :types
  has_and_belongs_to_many :project_types
  has_and_belongs_to_many :countries
  has_and_belongs_to_many :regions
  has_one :sector
  searchkick

  def search_data
      {
        title: title,
        country: country,
        client: client,
        sector_id: sector_id,
        region: region,
        owner: owner,
        current_phase: current_phase,
        responsible: responsible
      }
  end
end

app/models/project_temp.rb
class ProjectTemp < ApplicationRecord
  searchkick

  def search_data
      {
        title: title,
        country: country,
        sector_name: sector_name,
        client: client,
        region: region,
        owner: owner,
        current_phase: current_phase,
        responsible: responsible
      }
  end
end

app/models/project_type.rb
class ProjectType < Category
  has_and_belongs_to_many :projects
  default_scope { where(kind: 'project_type') }
end

app/models/region.rb
class Region < Category
  has_and_belongs_to_many :biddings
  has_and_belongs_to_many :projects
  default_scope { where(kind: 'region') }
end

app/models/report.rb
class Report < ApplicationRecord

  has_attached_file :image, styles: { medium: "270x300!", thumb: "100x100!" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/reporter.rb
class Reporter < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/request.rb
class Request < ApplicationRecord
  validates_uniqueness_of :email
  validates_presence_of :contact_person, :email, :phone, :business
end

app/models/sector.rb
class Sector < ApplicationRecord
  has_and_belongs_to_many :projects
  has_and_belongs_to_many :biddings

end

app/models/suscription.rb
class Suscription < ApplicationRecord
  validates_uniqueness_of :email
  validates_presence_of :name, :email, :city

end

app/models/type.rb
class Type < Category
  has_and_belongs_to_many :projects
  default_scope { where(kind: 'types') }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable :recoverable
  devise :database_authenticatable,
          :rememberable, :trackable, :validatable, :recoverable
end

app/controllers/admin/sectors_controller.rb
class Admin::SectorsController < Admin::ApplicationController
  before_action :set_sector, only: [:show, :edit, :update, :destroy]

  # GET /sectors
  # GET /sectors.json
  def index
    @sectors = Sector.all
  end

  # GET /sectors/1
  # GET /sectors/1.json
  def show
  end

  # GET /sectors/new
  def new
    @sector = Sector.new
  end

  # GET /sectors/1/edit
  def edit
  end

  # POST /sectors
  # POST /sectors.json
  def create
    @sector = Sector.new(sector_params)

    respond_to do |format|
      if @sector.save
        format.html { redirect_to [:admin, @sector], notice: 'Sector was successfully created.' }
        format.json { render :show, status: :created, location: @sector }
      else
        format.html { render :new }
        format.json { render json: @sector.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sectors/1
  # PATCH/PUT /sectors/1.json
  def update
    respond_to do |format|
      if @sector.update(sector_params)
        format.html { redirect_to [:admin, @sector], notice: 'Sector was successfully updated.' }
        format.json { render :show, status: :ok, location: @sector }
      else
        format.html { render :edit }
        format.json { render json: @sector.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sectors/1
  # DELETE /sectors/1.json
  def destroy
    @sector.destroy
    respond_to do |format|
      format.html { redirect_to admin_sectors_url, notice: 'Sector was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sector
      @sector = Sector.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sector_params
      params.require(:sector).permit(:name)
    end
end

app/helpers/sectors_helper.rb
module SectorsHelper
end

app/views/admin/sectors/_form.html.erb
<%= form_for [:admin, @sector], :html => { :class => "form-horizontal sector" } do |f| %>

  <% if @sector.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@sector.errors.count, "error") %> prohibited this sector from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @sector.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                admin_sectors_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/admin/sectors/edit.html.erb
<%- model_class = Sector -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/sectors/index.html.erb
<%- model_class = Sector -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @sectors.each do |sector| %>
      <tr>
        <td><%= link_to sector.id, admin_sector_path(sector) %></td>
        <td><%= sector.name %></td>
        <td><%=l sector.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      admin_sector_path(sector), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_admin_sector_path(sector), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      admin_sector_path(sector),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_admin_sector_path,
            :class => 'btn btn-primary' %>

app/views/admin/sectors/new.html.erb
<%- model_class = Sector -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/sectors/show.html.erb
<%- model_class = Sector -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @sector.name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              admin_sectors_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_admin_sector_path(@sector), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              admin_sector_path(@sector),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>