config/routes.rb
Rails.application.routes.draw do

  resources :requests, only: [:new, :create]
  devise_for :admins
  root to: "user/home#index"

  # resources :reports
  # resources :newsletters
  devise_for :reporters
  resources :suscriptions, only:[:new, :create]
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/reporter', to: 'reporter/application#index'
  get '/quienes-somos', to: 'application#about'
  get '/contacto', to: 'application#contact'
  get '/noticias', to: 'application#reports'
  get '/admin', to: 'admin/application#index'
  get '/user', to: 'user/home#index'
  get '/admin/search', to: 'admin/application#search'




  namespace :admin do
    resources :biddings
    resources :projects
    resources :businesses
    resources :categories
    resources :project_temps
    resources :bidding_temps
    resources :requests, only:[:show, :index, :destroy]
    resources :sectors

  end

  namespace :user do
    resources :project_temps, only:[:show, :index]
    resources :bidding_temps, only:[:show, :index]
    resources :projects, only:[:show, :index]
  end

  namespace :reporter do
    resources :suscriptions, only:[:show, :index]
    resources :reports
    resources :newsletters do
      member do
        put :send_by_email
      end
    end
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/bidding.rb
class Bidding < ApplicationRecord
  has_and_belongs_to_many :items_involved
  has_one :business
  has_one :country
  has_one :sector
end

app/models/bidding_temp.rb
class BiddingTemp < ApplicationRecord
  searchkick

  def search_data
      {
        title: title,
        country: country,
        sector: sector,
        bidding_company: bidding_company
      }
  end
end

app/models/business.rb
class Business < ApplicationRecord
  has_and_belongs_to_many :biddings
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :projects_categories 
  enum kind: [:item, :types, :adjudications, :main_works, :main_services, :main_teams, :main_supplies, :items_involved,
              :client, :owner, :region, :country, :project_type]
end

app/models/client.rb
class Client < Category
end

app/models/country.rb
class Country < Category
  has_and_belongs_to_many :biddings
  has_and_belongs_to_many :projects
  default_scope { where(kind: 'country') }
end

app/models/item.rb
class Item < Category
  has_and_belongs_to_many :projects
  default_scope { where(kind: 'item') }
end

app/models/main_work.rb
class MainWork < Category
  has_and_belongs_to_many :projects
  default_scope { where(kind: 'main_works') }
end

app/models/newsletter.rb
class Newsletter < ApplicationRecord
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/project.rb
class Project < ApplicationRecord
  has_and_belongs_to_many :items
  has_and_belongs_to_many :types
  has_and_belongs_to_many :project_types
  has_and_belongs_to_many :countries
  has_and_belongs_to_many :regions
  has_one :sector
  searchkick

  def search_data
      {
        title: title,
        country: country,
        client: client,
        sector_id: sector_id,
        region: region,
        owner: owner,
        current_phase: current_phase,
        responsible: responsible
      }
  end
end

app/models/project_temp.rb
class ProjectTemp < ApplicationRecord
  searchkick

  def search_data
      {
        title: title,
        country: country,
        sector_name: sector_name,
        client: client,
        region: region,
        owner: owner,
        current_phase: current_phase,
        responsible: responsible
      }
  end
end

app/models/project_type.rb
class ProjectType < Category
  has_and_belongs_to_many :projects
  default_scope { where(kind: 'project_type') }
end

app/models/region.rb
class Region < Category
  has_and_belongs_to_many :biddings
  has_and_belongs_to_many :projects
  default_scope { where(kind: 'region') }
end

app/models/report.rb
class Report < ApplicationRecord

  has_attached_file :image, styles: { medium: "270x300!", thumb: "100x100!" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/reporter.rb
class Reporter < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/request.rb
class Request < ApplicationRecord
  validates_uniqueness_of :email
  validates_presence_of :contact_person, :email, :phone, :business
end

app/models/sector.rb
class Sector < ApplicationRecord
  has_and_belongs_to_many :projects
  has_and_belongs_to_many :biddings

end

app/models/suscription.rb
class Suscription < ApplicationRecord
  validates_uniqueness_of :email
  validates_presence_of :name, :email, :city

end

app/models/type.rb
class Type < Category
  has_and_belongs_to_many :projects
  default_scope { where(kind: 'types') }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable :recoverable
  devise :database_authenticatable,
          :rememberable, :trackable, :validatable, :recoverable
end

app/controllers/admin/biddings_controller.rb
class Admin::BiddingsController < Admin::ApplicationController
  before_action :set_bidding, only: [:show, :edit, :update, :destroy]

  # GET /biddings
  # GET /biddings.json
  def index
    @biddings = Bidding.all
  end

  # GET /biddings/1
  # GET /biddings/1.json
  def show
  end

  # GET /biddings/new
  def new
    @bidding = Bidding.new
  end

  # GET /biddings/1/edit
  def edit
  end

  # POST /biddings
  # POST /biddings.json
  def create
    @bidding = Bidding.new(bidding_params)

    respond_to do |format|
      if @bidding.save
        format.html { redirect_to [:admin, @bidding], notice: 'Bidding was successfully created.' }
        format.json { render :show, status: :created, location: @bidding }
      else
        format.html { render :new }
        format.json { render json: @bidding.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /biddings/1
  # PATCH/PUT /biddings/1.json
  def update
    respond_to do |format|
      if @bidding.update(bidding_params)
        format.html { redirect_to [:admin, @bidding], notice: 'Bidding was successfully updated.' }
        format.json { render :show, status: :ok, location: @bidding }
      else
        format.html { render :edit }
        format.json { render json: @bidding.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /biddings/1
  # DELETE /biddings/1.json
  def destroy
    @bidding.destroy
    respond_to do |format|
      format.html { redirect_to biddings_url, notice: 'Bidding was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bidding
      @bidding = Bidding.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bidding_params
      params.require(:bidding).permit(:publication_title, :country_id, :sector_id, :location, :bussiness_id, :description, :contact_name, :contact_job, :contact_email, :contact_phone, :contact_address, :other)
    end
end

app/helpers/biddings_helper.rb
module BiddingsHelper
end

app/views/admin/biddings/_form.html.erb
<%= form_for [:admin, @bidding], :html => { :class => "form-horizontal bidding" } do |f| %>

  <% if @bidding.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@bidding.errors.count, "error") %> prohibited this bidding from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @bidding.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :publication_title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :publication_title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:publication_title) %>
  </div>

  <div class="form-group">
    <%= f.label :country, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :country, options_for_select(Country.all.map{|i| [i.name, i.id]}), :class => 'form-control', multiple: true %>
    </div>
    <%=f.error_span(:country) %>
  </div>

  <div class="form-group">
    <%= f.label :sector, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :sector, options_for_select(Sector.all.map{|i| [i.name, i.id]}), :class => 'form-control', multiple: true %>
    </div>
    <%=f.error_span(:sector) %>
  </div>
  <div class="form-group">
    <%= f.label :location, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :location, :class => 'form-control' %>
    </div>
    <%=f.error_span(:location) %>
  </div>
  <div class="form-group">
    <%= f.label :business_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :business_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:business_id) %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>
  <div class="form-group">
    <%= f.label :contact_name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :contact_name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:contact_name) %>
  </div>
  <div class="form-group">
    <%= f.label :contact_job, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :contact_job, :class => 'form-control' %>
    </div>
    <%=f.error_span(:contact_job) %>
  </div>
  <div class="form-group">
    <%= f.label :contact_email, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :contact_email, :class => 'form-control' %>
    </div>
    <%=f.error_span(:contact_email) %>
  </div>
  <div class="form-group">
    <%= f.label :contact_phone, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :contact_phone, :class => 'form-control' %>
    </div>
    <%=f.error_span(:contact_phone) %>
  </div>
  <div class="form-group">
    <%= f.label :contact_address, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :contact_address, :class => 'form-control' %>
    </div>
    <%=f.error_span(:contact_address) %>
  </div>
  <div class="form-group">
    <%= f.label :other, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :other, :class => 'form-control' %>
    </div>
    <%=f.error_span(:other) %>
  </div>









  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                admin_biddings_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/admin/biddings/edit.html.erb
<%- model_class = Bidding -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/biddings/index.html.erb
<%- model_class = Bidding -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:publication_title) %></th>
      <th><%= model_class.human_attribute_name(:country) %></th>
      <th><%= model_class.human_attribute_name(:sector) %></th>
      <th><%= model_class.human_attribute_name(:location) %></th>
      <th><%= model_class.human_attribute_name(:business_id) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:contact_name) %></th>
      <th><%= model_class.human_attribute_name(:contact_job) %></th>
      <th><%= model_class.human_attribute_name(:contact_email) %></th>
      <th><%= model_class.human_attribute_name(:contact_phone) %></th>
      <th><%= model_class.human_attribute_name(:contact_address) %></th>
      <th><%= model_class.human_attribute_name(:other) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @biddings.each do |bidding| %>
      <tr>
        <td><%= link_to bidding.id, admin_bidding_path(bidding) %></td>
        <td><%= bidding.publication_title %></td>
        <td><%= bidding.country %></td>
        <td><%= bidding.sector %></td>
        <td><%= bidding.location %></td>
        <td><%= bidding.business_id %></td>
        <td><%= bidding.description %></td>
        <td><%= bidding.contact_name %></td>
        <td><%= bidding.contact_job %></td>
        <td><%= bidding.contact_email %></td>
        <td><%= bidding.contact_phone %></td>
        <td><%= bidding.contact_address %></td>
        <td><%= bidding.other %></td>
        <td><%=l bidding.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      admin_bidding_path(bidding), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_admin_bidding_path(bidding), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      admin_bidding_path(bidding),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_admin_bidding_path,
            :class => 'btn btn-primary' %>

app/views/admin/biddings/new.html.erb
<%- model_class = Bidding -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/biddings/show.html.erb
<%- model_class = Bidding -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:publication_title) %>:</strong></dt>
  <dd><%= @bidding.publication_title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:country) %>:</strong></dt>
  <dd><%= @bidding.country %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sector) %>:</strong></dt>
  <dd><%= @bidding.sector %></dd>
  <dt><strong><%= model_class.human_attribute_name(:location) %>:</strong></dt>
  <dd><%= @bidding.location %></dd>
  <dt><strong><%= model_class.human_attribute_name(:business_id) %>:</strong></dt>
  <dd><%= @bidding.business_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @bidding.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:contact_name) %>:</strong></dt>
  <dd><%= @bidding.contact_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:contact_job) %>:</strong></dt>
  <dd><%= @bidding.contact_job %></dd>
  <dt><strong><%= model_class.human_attribute_name(:contact_email) %>:</strong></dt>
  <dd><%= @bidding.contact_email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:contact_phone) %>:</strong></dt>
  <dd><%= @bidding.contact_phone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:contact_address) %>:</strong></dt>
  <dd><%= @bidding.contact_address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:other) %>:</strong></dt>
  <dd><%= @bidding.other %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              admin_biddings_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_admin_bidding_path(@bidding), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              admin_bidding_path(@bidding),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>