config/routes.rb
Rails.application.routes.draw do

  resources :requests, only: [:new, :create]
  devise_for :admins
  root to: "user/home#index"

  # resources :reports
  # resources :newsletters
  devise_for :reporters
  resources :suscriptions, only:[:new, :create]
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/reporter', to: 'reporter/application#index'
  get '/quienes-somos', to: 'application#about'
  get '/contacto', to: 'application#contact'
  get '/noticias', to: 'application#reports'
  get '/admin', to: 'admin/application#index'
  get '/user', to: 'user/home#index'
  get '/admin/search', to: 'admin/application#search'




  namespace :admin do
    resources :biddings
    resources :projects
    resources :businesses
    resources :categories
    resources :project_temps
    resources :bidding_temps
    resources :requests, only:[:show, :index, :destroy]
    resources :sectors

  end

  namespace :user do
    resources :project_temps, only:[:show, :index]
    resources :bidding_temps, only:[:show, :index]
    resources :projects, only:[:show, :index]
  end

  namespace :reporter do
    resources :suscriptions, only:[:show, :index]
    resources :reports
    resources :newsletters do
      member do
        put :send_by_email
      end
    end
  end

end

app/models/project.rb
class Project < ApplicationRecord
  has_and_belongs_to_many :items
  has_and_belongs_to_many :types
  has_and_belongs_to_many :project_types
  has_and_belongs_to_many :countries
  has_and_belongs_to_many :regions
  has_one :sector
  searchkick

  def search_data
      {
        title: title,
        country: country,
        client: client,
        sector_id: sector_id,
        region: region,
        owner: owner,
        current_phase: current_phase,
        responsible: responsible
      }
  end
end

app/models/project_type.rb
class ProjectType < Category
  has_and_belongs_to_many :projects
  default_scope { where(kind: 'project_type') }
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to [:admin, @project], notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to [:admin, @project], notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to admin_projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :country, :region, :sector_id, :investment, :production, :unit_production, :location, :description, :current_phase,
         :responsible, :contract_type, :latest_information, :contact_name, :contact_company, :contact_job, :contact_phone, :contact_address, :history, :client,
         :type, :owner, :main_works, :adjudications, :project_type_ids)
    end
end

app/controllers/user/projects_controller.rb
class User::ProjectsController < User::ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
    @found_sector =  Project.search(params['sector_name'], fields: [:sector_name])
    if @found_sector.length == 0
      @found_sector = Project.all
    end
    # query = params[:query].presence || "*"
    # conditions = {}
    # conditions[:sector_name] = params[:sector_name] if params[:sector_name].present?
    # conditions[:country] = params[:country] if params[:country].present?
    # @found_sector = Project.search query, where: conditions

    @found_sector = Project.search(params[:sector_name], fields: [:sector_name]).results &
                    Project.search(params[:country], fields: [:country]).results &
                    Project.search(params[:region], fields: [:region]).results
    if @found_sector.length == 0
      @found_sector = Project.all
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    respond_to do |format|
     format.html
     format.pdf do
     render pdf: "Your_filename",
     template: "user/projects/show.html.erb",
     layout: 'pdf.html'

   end
  end

  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to [:user, @project], notice: 'Project temp was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to [:user, @project], notice: 'Project temp was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to user_projects_url, notice: 'Project temp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :detail_title, :country, :region, :sector_name, :types, :investment, :production, :client, :owner, :location, :description, :current_phase, :responsible, :contract_type, :latest_information, :contact_name, :contact_company, :contact_job, :contact_phone, :contact_address, :full_contact, :adjudications, :history, :main_works, :main_teams, :main_supplies, :main_services)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/admin/projects/_form.html.erb
<%= form_for [:admin, @project], :html => { :class => "form-horizontal project" } do |f| %>

  <% if @project.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>
  <div class="form-group">
    <%= f.label :country, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :country, options_for_select(Country.all.map{|i| [i.name, i.name]}), :class => 'form-control', multiple: true %>
    </div>
    <%=f.error_span(:main_works) %>
  </div>

  <div class="form-group">
    <%= f.label :sector_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :sector_id, options_for_select(Sector.all.map{|i| [i.name, i.id]}, @project.sector_id), :class => 'form-control', multiple: true %>
    </div>
    <%=f.error_span(:sector) %>
  </div>
  <div class="form-group">
    <%= f.label :region, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :region, options_for_select(Region.all.map{|i| [i.name, i.name]}), :class => 'form-control', multiple: true %>
    </div>
    <%=f.error_span(:region) %>
  </div>

  <div class="form-group">
    <%= f.label :investment, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :investment, :class => 'form-control' %>
    </div>
    <%=f.error_span(:investment) %>
  </div>
  <div class="form-group">
    <%= f.label :production, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :production, :class => 'form-control' %>
    </div>
    <%=f.error_span(:production) %>
  </div>
  <div class="form-group">
    <%= f.label :unit_production, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :unit_production, :class => 'form-control' %>
    </div>
    <%=f.error_span(:unit_production) %>
  </div>
  <div class="form-group">
    <%= f.label :location, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :location, :class => 'form-control' %>
    </div>
    <%=f.error_span(:location) %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>
  <div class="form-group">
    <%= f.label :current_phase, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :current_phase, :class => 'form-control' %>
    </div>
    <%=f.error_span(:current_phase) %>
  </div>
  <div class="form-group">
    <%= f.label :responsible, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :responsible, :class => 'form-control' %>
    </div>
    <%=f.error_span(:responsible) %>
  </div>
  <div class="form-group">
    <%= f.label :contract_type, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :contract_type, :class => 'form-control' %>
    </div>
    <%=f.error_span(:contract_type) %>
  </div>
  <div class="form-group">
    <%= f.label :latest_information, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :latest_information, :class => 'form-control' %>
    </div>
    <%=f.error_span(:latest_information) %>
  </div>
  <div class="form-group">
    <%= f.label :contact_name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :contact_name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:contact_name) %>
  </div>
  <div class="form-group">
    <%= f.label :contact_company, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :contact_company, :class => 'form-control' %>
    </div>
    <%=f.error_span(:contact_company) %>
  </div>
  <div class="form-group">
    <%= f.label :contact_job, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :contact_job, :class => 'form-control' %>
    </div>
    <%=f.error_span(:contact_job) %>
  </div>
  <div class="form-group">
    <%= f.label :contact_phone, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :contact_phone, :class => 'form-control' %>
    </div>
    <%=f.error_span(:contact_phone) %>
  </div>
  <div class="form-group">
    <%= f.label :contact_address, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :contact_address, :class => 'form-control' %>
    </div>
    <%=f.error_span(:contact_address) %>
  </div>
  <div class="form-group">
    <%= f.label :history, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :history, :class => 'form-control' %>
    </div>
    <%=f.error_span(:history) %>
  </div>
  <div class="form-group">
    <%= f.label :project_types, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.collection_select(:project_type_ids, ProjectType.all, :id, :name, {:prompt => "Please Select a Type"}, {:multiple => true}) %>
    </div>
    <%=f.error_span(:project_types) %>
  </div>
  <div class="form-group">
      <%= f.label :client, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.text_field :client, :class => 'form-control' %>
      </div>
      <%=f.error_span(:client) %>
    </div>
  <div class="form-group">
    <%= f.label :owner, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :owner, :class => 'form-control' %>
    </div>
    <%=f.error_span(:owner) %>
  </div>
  <div class="form-group">
    <%= f.label :adjudications, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :adjudications, :class => 'form-control' %>
    </div>
    <%=f.error_span(:adjudications) %>
  </div>
  <div class="form-group">
    <%= f.label :main_works, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :main_works, :class => 'form-control' %>
    </div>
    <%=f.error_span(:main_works) %>
  </div>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                admin_projects_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/admin/projects/edit.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/projects/index.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:country) %></th>
      <th><%= model_class.human_attribute_name(:region) %></th>
      <th><%= model_class.human_attribute_name(:sector_name) %></th>
      <th><%= model_class.human_attribute_name(:investment) %></th>
      <th><%= model_class.human_attribute_name(:production) %></th>
      <!-- <th><%= model_class.human_attribute_name(:unit_production) %></th> -->
      <th><%= model_class.human_attribute_name(:current_phase) %></th>
      <th><%= model_class.human_attribute_name(:responsible) %></th>
      <th><%= model_class.human_attribute_name(:contract_type) %></th>
      <th><%= model_class.human_attribute_name(:contact_name) %></th>
      <th><%= model_class.human_attribute_name(:contact_company) %></th>
      <th><%= model_class.human_attribute_name(:contact_job) %></th>
      <th><%= model_class.human_attribute_name(:contact_phone) %></th>
      <th><%= model_class.human_attribute_name(:contact_address) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.id, admin_project_path(project) %></td>
        <td><%= project.title %></td>
        <td><%= project.country %></td>
        <td><%= project.region %></td>
        <td>
          <% if !Sector.find_by_id(project.sector_id).nil? %>
            <%= Sector.find_by_id(project.sector_id).name %></td>
          <% else %>
            <%= 'Sin sector' %>
          <% end %>
        <td><%= 'US$ ' + project.investment.to_s + ' Millones' %></td>
        <td><%= project.production %></td>
        <!-- <td><%= project.unit_production %></td> -->
        <td><%= project.current_phase %></td>
        <td><%= project.responsible %></td>
        <td><%= project.contract_type %></td>
        <td><%= project.contact_name %></td>
        <td><%= project.contact_company %></td>
        <td><%= project.contact_job %></td>
        <td><%= project.contact_phone %></td>
        <td><%= project.contact_address %></td>
        <td><%= project.created_at.strftime("%d %b, %Y")  %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      admin_project_path(project), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_admin_project_path(project), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      admin_project_path(project),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_admin_project_path,
            :class => 'btn btn-primary' %>

app/views/admin/projects/new.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/projects/show.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @project.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:country) %>:</strong></dt>
  <dd><%= @project.country %></dd>
  <dt><strong><%= model_class.human_attribute_name(:region) %>:</strong></dt>
  <dd><%= @project.region %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sector) %>:</strong></dt>
  <dd><%= Sector.find_by_id(@project.sector_id).name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:project_type) %>:</strong></dt>
  <dd><% @project.project_types.each do |ps| %>
        <%= ps.name %>
      <% end %>
  </dd>
  <dt><strong><%= model_class.human_attribute_name(:investment) %>:</strong></dt>
  <dd><%= 'US$ ' + @project.investment.to_s + ' Millones'%></dd>
  <dt><strong><%= model_class.human_attribute_name(:production) %>:</strong></dt>
  <dd><%= @project.production %></dd>
  <dt><strong><%= model_class.human_attribute_name(:unit_production) %>:</strong></dt>
  <dd><%= @project.unit_production %></dd>
  <dt><strong><%= model_class.human_attribute_name(:location) %>:</strong></dt>
  <dd><%= @project.location %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @project.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:current_phase) %>:</strong></dt>
  <dd><%= @project.current_phase %></dd>
  <dt><strong><%= model_class.human_attribute_name(:responsible) %>:</strong></dt>
  <dd><%= @project.responsible %></dd>
  <dt><strong><%= model_class.human_attribute_name(:contract_type) %>:</strong></dt>
  <dd><%= @project.contract_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:latest_information) %>:</strong></dt>
  <dd><%= @project.latest_information %></dd>
  <dt><strong><%= model_class.human_attribute_name(:contact_name) %>:</strong></dt>
  <dd><%= @project.contact_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:contact_company) %>:</strong></dt>
  <dd><%= @project.contact_company %></dd>
  <dt><strong><%= model_class.human_attribute_name(:contact_job) %>:</strong></dt>
  <dd><%= @project.contact_job %></dd>
  <dt><strong><%= model_class.human_attribute_name(:contact_phone) %>:</strong></dt>
  <dd><%= @project.contact_phone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:contact_address) %>:</strong></dt>
  <dd><%= @project.contact_address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:history) %>:</strong></dt>
  <dd><%= @project.history %></dd>
  <dt><strong><%= model_class.human_attribute_name(:adjudications) %>:</strong></dt>
  <dd><%= @project.adjudications %></dd>
  <dt><strong><%= model_class.human_attribute_name(:main_works) %>:</strong></dt>
  <dd><%= @project.main_works %></dd>
  <dt><strong><%= model_class.human_attribute_name(:owner) %>:</strong></dt>
  <dd><%= @project.owner %></dd>
  <dt><strong><%= model_class.human_attribute_name(:clients) %>:</strong></dt>
  <dd><%= @project.client %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              admin_projects_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_admin_project_path(@project), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              admin_project_path(@project),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>